### ISSUE TITLE
[Compilation] Behavior with webpack 4 `minimize`

### ISSUE THREAD

**Issue by LeonardDrs** [nicolashemonic/rtl-css-transform-webpack-plugin#2]
Hi!

I noticed that this plugin didn't work with webpack `minimize`.
Here's a fix:
#1

**Comment by LeonardDrs** [comment]
If you look closely at your plugin, your `tests/cases/minimize/expected.css` is wrong (rtlcss rules are ignored), so you actually did reproduce.

**Comment by nicolashemonic** [comment]
Oups, big mistake 😅
Thank you for the reporting!
I pushed a correction based on your suggestion using new hooks api of Webpack v4.
The `v1.0.6` is also published on npm.
Let me know if is good to you.

**Comment by LeonardDrs** [comment]
Works like a charm, thank you

**Comment by nicolashemonic** [comment]
You're welcome
